local ok, _ = pcall(require, 'emmet')

if not ok then
    vim.notify_once('emmet not installed')
    return {}
end

vim.cmd[[
    let g:user_emmet_settings = {
\  'html': {
\    'extends': 'html',
\    'variables': {
\      'lang': 'en',
\    },
\    'default_attributes': {
\      'option': {'value': v:null},
\      'textarea': {'id': v:null, 'name': v:null, 'cols': 10, 'rows': 10},
\    },
\    'snippets': {
\      '!': "<!DOCTYPE html>\n"
\              ."<html>\n"
\              ."<head>\n"
\              ."\t<meta charset=\"${charset}">\n"
\              ."\t<title>Document</title>\n"
\              ."\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
\              ."</head>\n"
\              ."<body>\n\t${child}|\n</body>\n"
\              ."</html>",
\      'html:5': 
\      'a': "<a href=\"${href}\">${child}</a>",
\      'abbr': "<abbr title=\"${title}\">${child}</abbr>",
\      'acronym': "<acronym title=\"${title}\">${child}</acronym>",
\      'address': "<address>${child}</address>",
\      'area': "<area alt=\"${alt}\" coords=\"${coords}\" href=\"${href}\" shape=\"${shape}\">",
\      'article': "<article>${child}</article>",
\      'aside': "<aside>${child}</aside>",
\      'audio': "<audio controls=\"controls\" src=\"${src}\">${child}</audio>",
\      'b': "<b>${child}</b>",
\      'base': "<base href=\"${href}\" target=\"${target}\">",
\      'bdi': "<bdi>${child}</bdi>",
\      'bdo': "<bdo dir=\"${dir}\">${child}</bdo>",
\      'blockquote': "<blockquote cite=\"${cite}\">${child}</blockquote>",
\      'body': "<body>${child}</body>",
\      'br': "<br>",
\      'button': "<button type=\"${type}\">${child}</button>",
\      'canvas': "<canvas height=\"${height}\" width=\"${width}\">${child}</canvas>",
\      'caption': "<caption>${child}</caption>",
\      'cite': "<cite>${child}</cite>",
\      'code': "<code>${child}</code>",
\      'col': "<col span=\"${span}\">",
\      'colgroup': "<colgroup>${child}</colgroup>",
\      'command': "<command icon=\"${icon}\" label=\"${label}\" type=\"${type}\">",
\      'datalist': "<datalist>${child}</datalist>",
\      'dd': "<dd>${child}</dd>",
\      'del': "<del datetime=\"${datetime}\">${child}</del>",
\      'details': "<details>${child}</details>",
\      'dfn': "<dfn>${child}</dfn>",
\      'div': "<div>${child}</div>",
\      'dl': "<dl>${child}</dl>",
\      'dt': "<dt>${child}</dt>",
\      'em': "<em>${child}</em>",
\      'embed': "<embed height=\"${height}\" src=\"${src}\" type=\"${type}\" width=\"${width}\">",
\      'fieldset': "<fieldset>${child}</fieldset>",
\      'figcaption': "<figcaption>${child}</figcaption>",
\      'figure': "<figure>${child}</figure>",
\      'footer': "<footer>${child}</footer>",
\      'form': "<form action=\"${action}\" method=\"${method}\">${child}</form>",
\      'h1': "<h1>${child}</h1>",
\      'h2': "<h2>${child}</h2>",
\      'h3': "<h3>${child}</h3>",
\      'h4': "<h4>${child}</h4>",
\      'h5': "<h5>${child}</h5>",
\      'h6': "<h6>${child}</h6>",
\      'head': "<head>${child}</head>",
\      'header': "<header>${child}</header>",
\      'hgroup': "<hgroup>${child}</hgroup>",
\      'hr': "<hr>",
\      'html': "<html>${child}</html>",
\      'i': "<i>${child}</i>",
\      'iframe': "<iframe height=\"${height}\" src=\"${src}\" width=\"${width}\">${child}</iframe>",
\      'img': "<img alt=\"${alt}\" height=\"${height}\" src=\"${src}\" width=\"${width}\">",
\      'input': "<input type=\"${type}\" value=\"${value}\">",
\      'ins': "<ins datetime=\"${datetime}\">${child}</ins>",
\      'kbd': "<kbd>${child}</kbd>",
\      'label': "<label for=\"${for}\">${child}</label>",
\      'legend': "<legend>${child}</legend>",
\      'li': "<li>${child}</li>",
\      'link': "<link href=\"${href}\" rel=\"${rel}\" type=\"${type}\">",
\      'main': "<main>${child}</main>",
\      'map': "<map name=\"${name}\">${child}</map>",
\      'mark': "<mark>${child}</mark>",
\      'menu': "<menu>${child}</menu>",
\      'menuitem': "<menuitem label=\"${label}\" type=\"${type}\">",
\      'meta': "<meta charset=\"${charset}\">",
\      'meter': "<meter value=\"${value}\">${child}</meter>",
\      'nav': "<nav>${child}</nav>",
\      'noscript': "<noscript>${child}</noscript>",
\      'object': "<object data=\"${data}\" type=\"${type}\">${child}</object>",
\      'ol': "<ol>${child}</ol>",
\      'optgroup': "<optgroup label=\"${label}\">${child}</optgroup>",
\      'option': "<option value=\"${value}\">${child}</option>",
\      'output': "<output for=\"${for}\" name=\"${name}\">${child}</output>",
\      'p': "<p>${child}</p>",
\      'param': "<param name=\"${name}\" value=\"${value}\">",
\      'pre': "<pre>${child}</pre>",
\      'progress': "<progress value=\"${value}\">${child}</progress>",
\      'q': "<q>${child}</q>",
\      'rp': "<rp>${child}</rp>",
\      'rt': "<rt>${child}</rt>",
\      'ruby': "<ruby>${child}</ruby>",
\      's': "<s>${child}</s>",
\      'samp': "<samp>${child}</samp>",
\      'script': "<script src=\"${src}\" type=\"${type}\">${child}</script>",
\      'section': "<section>${child}</section>",
\      'select': "<select>${child}</select>",
\      'small': "<small>${child}</small>",
\      'source': "<source src=\"${src}\" type=\"${type}\">",
\      'span': "<span>${child}</span>",
\      'strong': "<strong>${child}</strong>",
\      'style': "<style type=\"${type}\">${child}</style>",
\      'sub': "<sub>${child}</sub>",
\      'summary': "<summary>${child}</summary>",
\      'sup': "<sup>${child}</sup>",
\      'table': "<table>${child}</table>",
\      'tbody': "<tbody>${child}</tbody>",
\      'td': "<td>${child}</td>",
\      'textarea': "<textarea>${child}</textarea>",
\      'tfoot': "<tfoot>${child}</tfoot>",
\      'th': "<th>${child}</th>",
\      'thead': "<thead>${child}</thead>",
\      'time': "<time datetime=\"${datetime}\">${child}</time>",
\      'title': "<title>${child}</title>",
\      'tr': "<tr>${child}</tr>",
\      'track': "<track src=\"${src}\" kind=\"${kind}\" srclang=\"${srclang}\" label=\"${label}\">",
\      'u': "<u>${child}</u>",
\      'ul': "<ul>${child}</ul>",
\      'var': "<var>${child}</var>",
\      'video': "<video src=\"${src}\" width=\"${width}\" height=\"${height}\" poster=\"${poster}\" preload=\"${preload}\" autoplay=\"${autoplay}\" loop=\"${loop}\" controls=\"${controls}\">${child}</video>",
\      'wbr': "<wbr>",
\    },
\  },
\}
]]

return {}
