vim.g.mapleader = " "
vim.o.background = "dark"
vim.o.termguicolors = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.writebackup = false
vim.o.ttyfast = true
vim.o.lazyredraw = true
vim.o.hidden = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.cmdheight = 3
vim.o.updatetime = 300
